spring.application.name=lab06-intro-spring

# Base H2 en mémoire (pour les tests et le développement)
spring.datasource.url=jdbc:h2:mem:produitsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# auto-create tables from entities
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
