spring.application.name=user-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/usermanager
spring.datasource.username=nexa
spring.datasource.password=nexa123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
